// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGc_Ip0EAuKeoWKVbkAP5dvfMR110PHQ',
    appId: '1:571354583788:web:b746ae32d64062f43e4bc9',
    messagingSenderId: '571354583788',
    projectId: 'mathmasters-f23c1',
    authDomain: 'mathmasters-f23c1.firebaseapp.com',
    databaseURL: 'https://mathmasters-f23c1-default-rtdb.firebaseio.com',
    storageBucket: 'mathmasters-f23c1.appspot.com',
    measurementId: 'G-RC3CL6PQF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQpi8oyOa_HRei_ioLXGQ4XbuLrxx3sk',
    appId: '1:571354583788:android:aa84b5b6a1b6934a3e4bc9',
    messagingSenderId: '571354583788',
    projectId: 'mathmasters-f23c1',
    databaseURL: 'https://mathmasters-f23c1-default-rtdb.firebaseio.com',
    storageBucket: 'mathmasters-f23c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWeFvu5efcS-LUB2NLybABA2aidXrAfbQ',
    appId: '1:571354583788:ios:b7505e56457c4fe83e4bc9',
    messagingSenderId: '571354583788',
    projectId: 'mathmasters-f23c1',
    databaseURL: 'https://mathmasters-f23c1-default-rtdb.firebaseio.com',
    storageBucket: 'mathmasters-f23c1.appspot.com',
    iosBundleId: 'com.example.mathmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWeFvu5efcS-LUB2NLybABA2aidXrAfbQ',
    appId: '1:571354583788:ios:b7505e56457c4fe83e4bc9',
    messagingSenderId: '571354583788',
    projectId: 'mathmasters-f23c1',
    databaseURL: 'https://mathmasters-f23c1-default-rtdb.firebaseio.com',
    storageBucket: 'mathmasters-f23c1.appspot.com',
    iosBundleId: 'com.example.mathmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkGc_Ip0EAuKeoWKVbkAP5dvfMR110PHQ',
    appId: '1:571354583788:web:7d7e2ae93c226ffb3e4bc9',
    messagingSenderId: '571354583788',
    projectId: 'mathmasters-f23c1',
    authDomain: 'mathmasters-f23c1.firebaseapp.com',
    databaseURL: 'https://mathmasters-f23c1-default-rtdb.firebaseio.com',
    storageBucket: 'mathmasters-f23c1.appspot.com',
    measurementId: 'G-HF40Y6S8N3',
  );
}
